### ISSUE TITLE
Request for omnipred model open source

### ISSUE THREAD

**Issue by pariskang** [google-research/optformer#61]
I am writing to kindly inquire about the possibility of open-sourcing the model. Making Omnipred available to the broader community could accelerate innovation, enable collaborative enhancements, and foster a deeper understanding of applying language models in unique ways.

**Comment by xingyousong** [comment]
Hi @pariskang, thanks for your interest. Unfortunately, it is a general policy that we can't open-source any Vizier-trained models, as internal confidential data can possibly be reverse-engineered. 

However, we designed OmniPred as a general purpose method for which users can pretrain over their own data, not restricted to only Vizier's hyperparameter tuning. For instance, it may be used to regress over graphs and other combinatorial objects. The single-task performance of the model is also quite competitive and does not need pretraining either. 

Hope this helps!
- Richard
