### ISSUE TITLE
can not use

### ISSUE THREAD

**Issue by MingqiFANG** [google-research/optformer#87]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_4107/3099025202.py in <cell line: 2>()
      1 import paddle
----> 2 from optformer.common.data import featurizers
      3 from optformer.common.serialization import numeric
      4 

/home/work/fangmingqi/utils/github_projects/optformer/optformer-main/optformer/common/data/featurizers/__init__.py in <module>
     16 
     17 from optformer.common.data.featurizers.base import Featurizer
---> 18 from optformer.common.data.featurizers.testing import IdentityFeaturizer

/home/work/fangmingqi/utils/github_projects/optformer/optformer-main/optformer/common/data/featurizers/testing.py in <module>
     20 
     21 
---> 22 class IdentityFeaturizer(base.Featurizer[str]):
     23   """Simply returns identity of string input."""
     24 

/home/work/fangmingqi/utils/github_projects/optformer/optformer-main/optformer/common/data/featurizers/testing.py in IdentityFeaturizer()
     23   """Simply returns identity of string input."""
     24 
---> 25   def to_features(self, obj: str, /) -> dict[str, tf.Tensor]:
     26     return {
     27         'inputs': tf.constant(obj, dtype=tf.string),

TypeError: 'type' object is not subscriptable

**Comment by xingyousong** [comment]
I believe you need the most up-to-date version of Python (which has updated typing rules).
